base_dir = "/var/lib/vmkube"
cluster_count = 2  # сколько кластеров?
worker_nodes_per_cluster = 2  # сколько воркер-нод на каждый кластер?
control_plane_nodes_per_cluster = 3  # сколько control-plane-нод на каждый кластер?

# Внимание! По памяти и по CPU возможен overcommit, по диску - нет.
[control_plane_node]
cpus = 4  # сколько cpu ядер на мастер ноде?
ram = 4096  # сколько ram на мастер ноде?
system_disk = 7  # сколько диска для докер образов и ephemeral storage?

[worker_node]
cpus = 4  # сколько cpu ядер на каждой воркер ноде?
ram = 8192  # сколько ram на каждой воркер ноде?
system_disk = 15  # сколько диска для докер образов и ephemeral storage?
storage_disk = 10  # сколько диска для pvc?

[virtual_network]
name = "talos-net"  # название виртуальной сети, в которой будут находиться виртульные машины
bridge = "talos-br0"  # название виртуального сетевого интерфейса, через который хост будет коммуницирвать с виртуальными машинами
subnet = "192.168.192.0"  # сеть будет с маской /21. т. е. к третьему октету ещё прибавится 7. из этой подсети будут браться адреса как для вм, так и для loadbalancer
